apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- grafana-svc-patch.yaml
- prometheus-svc-patch.yaml
- prometheus-storage-patch.yaml
- prometheus-networkpolicy-patch.yaml
- grafana-networkpolicy-patch.yaml
- grafana-deployment-patch.yaml

# - datasource-patch.yaml

resources:
  - ../../manifests/
  - ../../manifests/setup
  - pvc-usage-dashboard.yaml
  - dashboard-configmap-provider.yaml
  # - dashboard-configmap-provider.yaml
  # - dashboard-configmap.yaml

patches:
  - target:
      kind: ClusterRole
      name: prometheus-k8s
    path: prometheus-clusterrolepatch.yaml




