apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- grafana-svc-patch.yaml
- prometheus-svc-patch.yaml
- prometheus-storage-patch.yaml
- prometheus-networkpolicy-patch.yaml
- grafana-networkpolicy-patch.yaml
- grafana-deployment-patch.yaml

resources:
  - ../../manifests/
  - ../../manifests/setup
  - dashboard-configmap-provider.yaml
  - dashboard-configmap.yaml



